//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Swigged.LLVM {

public enum Linkage {
  ExternalLinkage,
  AvailableExternallyLinkage,
  LinkOnceAnyLinkage,
  LinkOnceODRLinkage,
  LinkOnceODRAutoHideLinkage,
  WeakAnyLinkage,
  WeakODRLinkage,
  AppendingLinkage,
  InternalLinkage,
  PrivateLinkage,
  DLLImportLinkage,
  DLLExportLinkage,
  ExternalWeakLinkage,
  GhostLinkage,
  CommonLinkage,
  LinkerPrivateLinkage,
  LinkerPrivateWeakLinkage
}

}
