//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Swigged.LLVM {

public partial struct OpInfoSymbol1 : System.IEquatable<OpInfoSymbol1> {
        public OpInfoSymbol1(global::System.IntPtr cPtr)
        {
            Value = cPtr;
        }

        public System.IntPtr Value;

        public bool Equals(OpInfoSymbol1 other)
        {
            return Value.Equals(other.Value);
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            return obj is OpInfoSymbol1 && Equals((OpInfoSymbol1)obj);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }

        public static bool operator ==(OpInfoSymbol1 left, OpInfoSymbol1 right)
        {
            return left.Equals(right);
        }

        public static bool operator !=(OpInfoSymbol1 left, OpInfoSymbol1 right)
        {
            return !left.Equals(right);
        }
    
}

}
