//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Swigged.LLVM {

public enum ValueKind {
  ArgumentValueKind,
  BasicBlockValueKind,
  MemoryUseValueKind,
  MemoryDefValueKind,
  MemoryPhiValueKind,
  FunctionValueKind,
  GlobalAliasValueKind,
  GlobalIFuncValueKind,
  GlobalVariableValueKind,
  BlockAddressValueKind,
  ConstantExprValueKind,
  ConstantArrayValueKind,
  ConstantStructValueKind,
  ConstantVectorValueKind,
  UndefValueValueKind,
  ConstantAggregateZeroValueKind,
  ConstantDataArrayValueKind,
  ConstantDataVectorValueKind,
  ConstantIntValueKind,
  ConstantFPValueKind,
  ConstantPointerNullValueKind,
  ConstantTokenNoneValueKind,
  MetadataAsValueValueKind,
  InlineAsmValueKind,
  InstructionValueKind
}

}
