//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Swigged.LLVM {

public enum DWARFSourceLanguage {
  DWARFSourceLanguageC89,
  DWARFSourceLanguageC,
  DWARFSourceLanguageAda83,
  DWARFSourceLanguageC_plus_plus,
  DWARFSourceLanguageCobol74,
  DWARFSourceLanguageCobol85,
  DWARFSourceLanguageFortran77,
  DWARFSourceLanguageFortran90,
  DWARFSourceLanguagePascal83,
  DWARFSourceLanguageModula2,
  DWARFSourceLanguageJava,
  DWARFSourceLanguageC99,
  DWARFSourceLanguageAda95,
  DWARFSourceLanguageFortran95,
  DWARFSourceLanguagePLI,
  DWARFSourceLanguageObjC,
  DWARFSourceLanguageObjC_plus_plus,
  DWARFSourceLanguageUPC,
  DWARFSourceLanguageD,
  DWARFSourceLanguagePython,
  DWARFSourceLanguageOpenCL,
  DWARFSourceLanguageGo,
  DWARFSourceLanguageModula3,
  DWARFSourceLanguageHaskell,
  DWARFSourceLanguageC_plus_plus_03,
  DWARFSourceLanguageC_plus_plus_11,
  DWARFSourceLanguageOCaml,
  DWARFSourceLanguageRust,
  DWARFSourceLanguageC11,
  DWARFSourceLanguageSwift,
  DWARFSourceLanguageJulia,
  DWARFSourceLanguageDylan,
  DWARFSourceLanguageC_plus_plus_14,
  DWARFSourceLanguageFortran03,
  DWARFSourceLanguageFortran08,
  DWARFSourceLanguageRenderScript,
  DWARFSourceLanguageBLISS,
  DWARFSourceLanguageMips_Assembler,
  DWARFSourceLanguageGOOGLE_RenderScript,
  DWARFSourceLanguageBORLAND_Delphi
}

}
