//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Swigged.LLVM {

public enum llvm_lto_status_t {
  _LTO_UNKNOWN,
  _LTO_OPT_SUCCESS,
  _LTO_READ_SUCCESS,
  _LTO_READ_FAILURE,
  _LTO_WRITE_FAILURE,
  _LTO_NO_TARGET,
  _LTO_NO_WORK,
  _LTO_MODULE_MERGE_FAILURE,
  _LTO_ASM_FAILURE,
  _LTO_NULL_OBJECT
}

}
